name: bolero
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - bedtools
  - biopython
  - dask
  - deeptools
  - htslib
  - ipywidgets
  - jupyterlab
  - pyarrow
  - pynndescent
  - pysam
  - pytorch
  - samtools
  - scikit-learn
  - seaborn
  - snakemake
  - torchvision
  - xarray
  - zarr
  - scikit-image
  - pip:
      - black
      - einops
      - isort
      - jupyterlab-code-formatter
      - jupyterlab_execute_time
      - papermill
      - qnorm
      - torchinfo
      - torchmetrics
      - scvi-tools
